/*
 * Copyright (C) 2017 juehv
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.jhit.opendiabetes.vault.testhelper;

import de.jhit.opendiabetes.vault.container.VaultEntry;
import de.jhit.opendiabetes.vault.container.VaultEntryAnnotation;
import de.jhit.opendiabetes.vault.container.VaultEntryType;
import de.jhit.opendiabetes.vault.util.TimestampUtils;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author juehv
 */
public class StaticDataset {

    public static List<VaultEntry> getStaticDataset() throws ParseException {
        List<VaultEntry> vaultEntries = new ArrayList<>();
        List<VaultEntryAnnotation> tmpAnnotations;
        tmpAnnotations = new ArrayList<>();
        tmpAnnotations.add(new VaultEntryAnnotation(VaultEntryAnnotation.TYPE.GLUCOSE_BG_METER_SERIAL));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG, TimestampUtils.createCleanTimestamp("2017.06.01-00:05", "yyyy.MM.dd-HH:mm"), 110.0, tmpAnnotations));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:06", "yyyy.MM.dd-HH:mm"), 95.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:06", "yyyy.MM.dd-HH:mm"), 82.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:06", "yyyy.MM.dd-HH:mm"), 82.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-00:06", "yyyy.MM.dd-HH:mm"), 22.0, 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-00:09", "yyyy.MM.dd-HH:mm"), 100.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:15", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-00:24", "yyyy.MM.dd-HH:mm"), 23.0, 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:24", "yyyy.MM.dd-HH:mm"), 41.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-00:24", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:24", "yyyy.MM.dd-HH:mm"), 41.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:25", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-00:33", "yyyy.MM.dd-HH:mm"), 9.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:35", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-00:35", "yyyy.MM.dd-HH:mm"), 23.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:35", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-00:39", "yyyy.MM.dd-HH:mm"), 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-00:42", "yyyy.MM.dd-HH:mm"), 20.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:45", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:45", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-00:45", "yyyy.MM.dd-HH:mm"), 24.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-00:54", "yyyy.MM.dd-HH:mm"), 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-00:55", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-00:55", "yyyy.MM.dd-HH:mm"), 24.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-00:55", "yyyy.MM.dd-HH:mm"), 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-00:57", "yyyy.MM.dd-HH:mm"), 0.65));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-00:58", "yyyy.MM.dd-HH:mm"), 0.65));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-01:00", "yyyy.MM.dd-HH:mm"), 0.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-01:02", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:05", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-01:08", "yyyy.MM.dd-HH:mm"), 19.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-01:09", "yyyy.MM.dd-HH:mm"), 44.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:14", "yyyy.MM.dd-HH:mm"), 24.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-01:14", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:15", "yyyy.MM.dd-HH:mm"), 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-01:24", "yyyy.MM.dd-HH:mm"), 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:25", "yyyy.MM.dd-HH:mm"), 25.0, 97.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:25", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-01:25", "yyyy.MM.dd-HH:mm"), 27.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-01:27", "yyyy.MM.dd-HH:mm"), 18.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:35", "yyyy.MM.dd-HH:mm"), 26.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-01:35", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:35", "yyyy.MM.dd-HH:mm"), 26.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:35", "yyyy.MM.dd-HH:mm"), 66.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-01:39", "yyyy.MM.dd-HH:mm"), 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 36.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 26.0, 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-01:45", "yyyy.MM.dd-HH:mm"), 21.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-01:54", "yyyy.MM.dd-HH:mm"), 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-01:55", "yyyy.MM.dd-HH:mm"), 26.0, 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:55", "yyyy.MM.dd-HH:mm"), 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-01:55", "yyyy.MM.dd-HH:mm"), 46.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:55", "yyyy.MM.dd-HH:mm"), 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-01:55", "yyyy.MM.dd-HH:mm"), 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-02:00", "yyyy.MM.dd-HH:mm"), 0.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:05", "yyyy.MM.dd-HH:mm"), 90.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:05", "yyyy.MM.dd-HH:mm"), 70.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-02:05", "yyyy.MM.dd-HH:mm"), 25.0, 39.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:05", "yyyy.MM.dd-HH:mm"), 70.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:05", "yyyy.MM.dd-HH:mm"), 70.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-02:06", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-02:09", "yyyy.MM.dd-HH:mm"), 44.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-02:10", "yyyy.MM.dd-HH:mm"), 41.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:14", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-02:14", "yyyy.MM.dd-HH:mm"), 48.0, 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:16", "yyyy.MM.dd-HH:mm"), 92.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-02:19", "yyyy.MM.dd-HH:mm"), 48.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-02:24", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:25", "yyyy.MM.dd-HH:mm"), 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:25", "yyyy.MM.dd-HH:mm"), 73.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-02:25", "yyyy.MM.dd-HH:mm"), 17.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-02:25", "yyyy.MM.dd-HH:mm"), 48.0, 35.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:25", "yyyy.MM.dd-HH:mm"), 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-02:26", "yyyy.MM.dd-HH:mm"), 0.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-02:36", "yyyy.MM.dd-HH:mm"), 53.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-02:36", "yyyy.MM.dd-HH:mm"), 43.0, 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-02:39", "yyyy.MM.dd-HH:mm"), 128.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-02:42", "yyyy.MM.dd-HH:mm"), 7.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:45", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-02:49", "yyyy.MM.dd-HH:mm"), 32.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-02:54", "yyyy.MM.dd-HH:mm"), 141.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-02:55", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-02:56", "yyyy.MM.dd-HH:mm"), 0.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-02:57", "yyyy.MM.dd-HH:mm"), 0.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-03:00", "yyyy.MM.dd-HH:mm"), 0.85));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:05", "yyyy.MM.dd-HH:mm"), 59.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-03:09", "yyyy.MM.dd-HH:mm"), 141.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:16", "yyyy.MM.dd-HH:mm"), 64.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-03:16", "yyyy.MM.dd-HH:mm"), 27.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-03:16", "yyyy.MM.dd-HH:mm"), 42.0, 97.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-03:21", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-03:24", "yyyy.MM.dd-HH:mm"), 156.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:25", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-03:27", "yyyy.MM.dd-HH:mm"), 13.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-03:35", "yyyy.MM.dd-HH:mm"), 42.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:35", "yyyy.MM.dd-HH:mm"), 65.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-03:35", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-03:39", "yyyy.MM.dd-HH:mm"), 172.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-03:40", "yyyy.MM.dd-HH:mm"), 9.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-03:45", "yyyy.MM.dd-HH:mm"), 28.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-03:45", "yyyy.MM.dd-HH:mm"), 42.0, 96.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:45", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-03:49", "yyyy.MM.dd-HH:mm"), 12.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-03:54", "yyyy.MM.dd-HH:mm"), 174.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-03:55", "yyyy.MM.dd-HH:mm"), 42.0, 87.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:55", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-03:55", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-03:55", "yyyy.MM.dd-HH:mm"), 34.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-04:00", "yyyy.MM.dd-HH:mm"), 0.85));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-04:01", "yyyy.MM.dd-HH:mm"), 50.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:06", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:06", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-04:06", "yyyy.MM.dd-HH:mm"), 42.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:06", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-04:09", "yyyy.MM.dd-HH:mm"), 181.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:15", "yyyy.MM.dd-HH:mm"), 65.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-04:24", "yyyy.MM.dd-HH:mm"), 199.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-04:25", "yyyy.MM.dd-HH:mm"), 42.0, 97.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:25", "yyyy.MM.dd-HH:mm"), 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:25", "yyyy.MM.dd-HH:mm"), 27.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-04:35", "yyyy.MM.dd-HH:mm"), 42.0, 91.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:35", "yyyy.MM.dd-HH:mm"), 31.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:35", "yyyy.MM.dd-HH:mm"), 65.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-04:39", "yyyy.MM.dd-HH:mm"), 213.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:45", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-04:45", "yyyy.MM.dd-HH:mm"), 43.0, 97.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:45", "yyyy.MM.dd-HH:mm"), 27.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-04:51", "yyyy.MM.dd-HH:mm"), 47.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-04:54", "yyyy.MM.dd-HH:mm"), 221.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-04:55", "yyyy.MM.dd-HH:mm"), 59.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-04:55", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-04:55", "yyyy.MM.dd-HH:mm"), 43.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-05:00", "yyyy.MM.dd-HH:mm"), 1.05));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:05", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-05:05", "yyyy.MM.dd-HH:mm"), 43.0, 80.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:05", "yyyy.MM.dd-HH:mm"), 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:05", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:05", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-05:09", "yyyy.MM.dd-HH:mm"), 222.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:15", "yyyy.MM.dd-HH:mm"), 30.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-05:15", "yyyy.MM.dd-HH:mm"), 42.0, 93.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:15", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-05:24", "yyyy.MM.dd-HH:mm"), 228.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:25", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:35", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:35", "yyyy.MM.dd-HH:mm"), 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:35", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-05:35", "yyyy.MM.dd-HH:mm"), 42.0, 108.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:35", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-05:38", "yyyy.MM.dd-HH:mm"), 13.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-05:39", "yyyy.MM.dd-HH:mm"), 233.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:45", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:45", "yyyy.MM.dd-HH:mm"), 57.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-05:45", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-05:45", "yyyy.MM.dd-HH:mm"), 43.0, 108.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-05:51", "yyyy.MM.dd-HH:mm"), 25.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-05:54", "yyyy.MM.dd-HH:mm"), 236.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-05:55", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-06:00", "yyyy.MM.dd-HH:mm"), 1.05));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:05", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-06:09", "yyyy.MM.dd-HH:mm"), 238.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:15", "yyyy.MM.dd-HH:mm"), 59.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-06:16", "yyyy.MM.dd-HH:mm"), 35.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-06:24", "yyyy.MM.dd-HH:mm"), 240.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-06:25", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:25", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-06:25", "yyyy.MM.dd-HH:mm"), 43.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:35", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-06:39", "yyyy.MM.dd-HH:mm"), 242.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:45", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-06:51", "yyyy.MM.dd-HH:mm"), 23.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-06:54", "yyyy.MM.dd-HH:mm"), 235.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-06:55", "yyyy.MM.dd-HH:mm"), 38.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-06:55", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-06:55", "yyyy.MM.dd-HH:mm"), 43.0, 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-07:00", "yyyy.MM.dd-HH:mm"), 1.15));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:05", "yyyy.MM.dd-HH:mm"), 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-07:05", "yyyy.MM.dd-HH:mm"), 31.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-07:05", "yyyy.MM.dd-HH:mm"), 43.0, 91.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-07:05", "yyyy.MM.dd-HH:mm"), 31.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-07:09", "yyyy.MM.dd-HH:mm"), 220.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-07:14", "yyyy.MM.dd-HH:mm"), 17.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-07:15", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:15", "yyyy.MM.dd-HH:mm"), 59.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-07:15", "yyyy.MM.dd-HH:mm"), 43.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-07:24", "yyyy.MM.dd-HH:mm"), 220.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:25", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-07:31", "yyyy.MM.dd-HH:mm"), 12.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:35", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-07:39", "yyyy.MM.dd-HH:mm"), 229.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-07:43", "yyyy.MM.dd-HH:mm"), 16.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:45", "yyyy.MM.dd-HH:mm"), 56.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-07:54", "yyyy.MM.dd-HH:mm"), 232.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-07:55", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-07:55", "yyyy.MM.dd-HH:mm"), 34.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-07:55", "yyyy.MM.dd-HH:mm"), 43.0, 88.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-07:59", "yyyy.MM.dd-HH:mm"), 7.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-08:00", "yyyy.MM.dd-HH:mm"), 1.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-08:04", "yyyy.MM.dd-HH:mm"), 219.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-08:05", "yyyy.MM.dd-HH:mm"), 43.0, 96.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:05", "yyyy.MM.dd-HH:mm"), 64.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-08:05", "yyyy.MM.dd-HH:mm"), 28.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-08:09", "yyyy.MM.dd-HH:mm"), 231.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-08:11", "yyyy.MM.dd-HH:mm"), 219.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-08:11", "yyyy.MM.dd-HH:mm"), 28.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-08:11", "yyyy.MM.dd-HH:mm"), 219.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-08:14", "yyyy.MM.dd-HH:mm"), 3.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-08:15", "yyyy.MM.dd-HH:mm"), 43.0, 97.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-08:15", "yyyy.MM.dd-HH:mm"), 27.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:16", "yyyy.MM.dd-HH:mm"), 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-08:24", "yyyy.MM.dd-HH:mm"), 228.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-08:25", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-08:25", "yyyy.MM.dd-HH:mm"), 44.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:26", "yyyy.MM.dd-HH:mm"), 55.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-08:36", "yyyy.MM.dd-HH:mm"), 22.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-08:36", "yyyy.MM.dd-HH:mm"), 44.0, 109.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:36", "yyyy.MM.dd-HH:mm"), 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-08:39", "yyyy.MM.dd-HH:mm"), 13.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-08:39", "yyyy.MM.dd-HH:mm"), 214.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:45", "yyyy.MM.dd-HH:mm"), 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-08:52", "yyyy.MM.dd-HH:mm"), 5.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-08:54", "yyyy.MM.dd-HH:mm"), 200.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-08:55", "yyyy.MM.dd-HH:mm"), 56.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-08:55", "yyyy.MM.dd-HH:mm"), 24.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-08:55", "yyyy.MM.dd-HH:mm"), 44.0, 102.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-08:57", "yyyy.MM.dd-HH:mm"), 27.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-09:00", "yyyy.MM.dd-HH:mm"), 1.3));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:05", "yyyy.MM.dd-HH:mm"), 25.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-09:05", "yyyy.MM.dd-HH:mm"), 45.0, 100.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:05", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-09:09", "yyyy.MM.dd-HH:mm"), 193.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:15", "yyyy.MM.dd-HH:mm"), 57.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-09:24", "yyyy.MM.dd-HH:mm"), 182.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_DEEP, TimestampUtils.createCleanTimestamp("2017.06.01-09:24", "yyyy.MM.dd-HH:mm"), 13.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:25", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:25", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-09:25", "yyyy.MM.dd-HH:mm"), 45.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:35", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-09:35", "yyyy.MM.dd-HH:mm"), 44.0, 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:35", "yyyy.MM.dd-HH:mm"), 36.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-09:37", "yyyy.MM.dd-HH:mm"), 17.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-09:39", "yyyy.MM.dd-HH:mm"), 171.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-09:45", "yyyy.MM.dd-HH:mm"), 43.0, 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:45", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:45", "yyyy.MM.dd-HH:mm"), 45.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-09:54", "yyyy.MM.dd-HH:mm"), 160.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-09:54", "yyyy.MM.dd-HH:mm"), 162.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:56", "yyyy.MM.dd-HH:mm"), 45.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-09:56", "yyyy.MM.dd-HH:mm"), 43.0, 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-09:56", "yyyy.MM.dd-HH:mm"), 45.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-09:56", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-10:00", "yyyy.MM.dd-HH:mm"), 1.1));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-10:01", "yyyy.MM.dd-HH:mm"), 169.0));
        tmpAnnotations = new ArrayList<>();
        tmpAnnotations.add(new VaultEntryAnnotation(VaultEntryAnnotation.TYPE.GLUCOSE_BG_METER_SERIAL));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG, TimestampUtils.createCleanTimestamp("2017.06.01-10:01", "yyyy.MM.dd-HH:mm"), 169.0, tmpAnnotations));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-10:02", "yyyy.MM.dd-HH:mm"), 1.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-10:06", "yyyy.MM.dd-HH:mm"), 38.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-10:06", "yyyy.MM.dd-HH:mm"), 41.0, 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-10:09", "yyyy.MM.dd-HH:mm"), 151.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-10:24", "yyyy.MM.dd-HH:mm"), 152.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-10:30", "yyyy.MM.dd-HH:mm"), 147.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-10:38", "yyyy.MM.dd-HH:mm"), 1.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-10:39", "yyyy.MM.dd-HH:mm"), 120.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-10:41", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-10:41", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-10:41", "yyyy.MM.dd-HH:mm"), 41.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-10:51", "yyyy.MM.dd-HH:mm"), 96.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-10:54", "yyyy.MM.dd-HH:mm"), 112.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-11:00", "yyyy.MM.dd-HH:mm"), 0.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:00", "yyyy.MM.dd-HH:mm"), 40.0, 28.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:00", "yyyy.MM.dd-HH:mm"), 79.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:01", "yyyy.MM.dd-HH:mm"), 84.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-11:09", "yyyy.MM.dd-HH:mm"), 128.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:10", "yyyy.MM.dd-HH:mm"), 60.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:10", "yyyy.MM.dd-HH:mm"), 36.0, 53.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:11", "yyyy.MM.dd-HH:mm"), 81.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-11:13", "yyyy.MM.dd-HH:mm"), 5.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-11:19", "yyyy.MM.dd-HH:mm"), 8.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:20", "yyyy.MM.dd-HH:mm"), 31.0, 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:20", "yyyy.MM.dd-HH:mm"), 59.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:21", "yyyy.MM.dd-HH:mm"), 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-11:24", "yyyy.MM.dd-HH:mm"), 147.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:30", "yyyy.MM.dd-HH:mm"), 67.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:30", "yyyy.MM.dd-HH:mm"), 28.0, 44.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:31", "yyyy.MM.dd-HH:mm"), 84.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-11:39", "yyyy.MM.dd-HH:mm"), 152.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:40", "yyyy.MM.dd-HH:mm"), 26.0, 49.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:40", "yyyy.MM.dd-HH:mm"), 63.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:41", "yyyy.MM.dd-HH:mm"), 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-11:51", "yyyy.MM.dd-HH:mm"), 87.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-11:51", "yyyy.MM.dd-HH:mm"), 24.0, 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-11:51", "yyyy.MM.dd-HH:mm"), 59.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-11:54", "yyyy.MM.dd-HH:mm"), 136.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-12:00", "yyyy.MM.dd-HH:mm"), 0.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-12:01", "yyyy.MM.dd-HH:mm"), 22.0, 43.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:01", "yyyy.MM.dd-HH:mm"), 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-12:01", "yyyy.MM.dd-HH:mm"), 67.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-12:09", "yyyy.MM.dd-HH:mm"), 116.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-12:11", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:11", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-12:11", "yyyy.MM.dd-HH:mm"), 22.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-12:14", "yyyy.MM.dd-HH:mm"), 111.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:21", "yyyy.MM.dd-HH:mm"), 80.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-12:24", "yyyy.MM.dd-HH:mm"), 110.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-12:27", "yyyy.MM.dd-HH:mm"), 113.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-12:30", "yyyy.MM.dd-HH:mm"), 48.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-12:30", "yyyy.MM.dd-HH:mm"), 22.0, 69.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:31", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-12:39", "yyyy.MM.dd-HH:mm"), 109.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-12:40", "yyyy.MM.dd-HH:mm"), 47.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-12:40", "yyyy.MM.dd-HH:mm"), 22.0, 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:41", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-12:51", "yyyy.MM.dd-HH:mm"), 20.0, 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-12:51", "yyyy.MM.dd-HH:mm"), 54.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-12:51", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-12:54", "yyyy.MM.dd-HH:mm"), 121.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-13:00", "yyyy.MM.dd-HH:mm"), 0.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:01", "yyyy.MM.dd-HH:mm"), 20.0, 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:01", "yyyy.MM.dd-HH:mm"), 52.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:01", "yyyy.MM.dd-HH:mm"), 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-13:09", "yyyy.MM.dd-HH:mm"), 148.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:11", "yyyy.MM.dd-HH:mm"), 19.0, 53.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:11", "yyyy.MM.dd-HH:mm"), 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:11", "yyyy.MM.dd-HH:mm"), 60.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:21", "yyyy.MM.dd-HH:mm"), 79.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:21", "yyyy.MM.dd-HH:mm"), 43.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:21", "yyyy.MM.dd-HH:mm"), 18.0, 75.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-13:24", "yyyy.MM.dd-HH:mm"), 174.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:31", "yyyy.MM.dd-HH:mm"), 19.0, 81.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:31", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:31", "yyyy.MM.dd-HH:mm"), 39.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:31", "yyyy.MM.dd-HH:mm"), 19.0, 81.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-13:39", "yyyy.MM.dd-HH:mm"), 190.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:41", "yyyy.MM.dd-HH:mm"), 43.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:41", "yyyy.MM.dd-HH:mm"), 19.0, 75.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:41", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-13:51", "yyyy.MM.dd-HH:mm"), 19.0, 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-13:51", "yyyy.MM.dd-HH:mm"), 36.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-13:51", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-13:54", "yyyy.MM.dd-HH:mm"), 197.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-14:00", "yyyy.MM.dd-HH:mm"), 0.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:01", "yyyy.MM.dd-HH:mm"), 19.0, 69.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:01", "yyyy.MM.dd-HH:mm"), 19.0, 69.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:01", "yyyy.MM.dd-HH:mm"), 80.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:01", "yyyy.MM.dd-HH:mm"), 48.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-14:09", "yyyy.MM.dd-HH:mm"), 198.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:11", "yyyy.MM.dd-HH:mm"), 41.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:11", "yyyy.MM.dd-HH:mm"), 18.0, 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:11", "yyyy.MM.dd-HH:mm"), 41.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:11", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:21", "yyyy.MM.dd-HH:mm"), 18.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:21", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:21", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-14:24", "yyyy.MM.dd-HH:mm"), 195.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:31", "yyyy.MM.dd-HH:mm"), 18.0, 96.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:31", "yyyy.MM.dd-HH:mm"), 68.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:31", "yyyy.MM.dd-HH:mm"), 28.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-14:39", "yyyy.MM.dd-HH:mm"), 194.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:41", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:41", "yyyy.MM.dd-HH:mm"), 18.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:41", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-14:51", "yyyy.MM.dd-HH:mm"), 68.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-14:51", "yyyy.MM.dd-HH:mm"), 31.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-14:51", "yyyy.MM.dd-HH:mm"), 18.0, 92.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-14:54", "yyyy.MM.dd-HH:mm"), 197.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-15:00", "yyyy.MM.dd-HH:mm"), 0.7));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:01", "yyyy.MM.dd-HH:mm"), 66.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-15:09", "yyyy.MM.dd-HH:mm"), 200.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-15:11", "yyyy.MM.dd-HH:mm"), 46.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:11", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-15:11", "yyyy.MM.dd-HH:mm"), 21.0, 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:21", "yyyy.MM.dd-HH:mm"), 84.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-15:24", "yyyy.MM.dd-HH:mm"), 202.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:31", "yyyy.MM.dd-HH:mm"), 84.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-15:31", "yyyy.MM.dd-HH:mm"), 59.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-15:31", "yyyy.MM.dd-HH:mm"), 19.0, 54.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-15:39", "yyyy.MM.dd-HH:mm"), 205.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-15:41", "yyyy.MM.dd-HH:mm"), 53.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-15:41", "yyyy.MM.dd-HH:mm"), 18.0, 62.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-15:41", "yyyy.MM.dd-HH:mm"), 53.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:41", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-15:51", "yyyy.MM.dd-HH:mm"), 40.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-15:51", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-15:51", "yyyy.MM.dd-HH:mm"), 18.0, 79.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-15:55", "yyyy.MM.dd-HH:mm"), 211.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-16:00", "yyyy.MM.dd-HH:mm"), 0.7));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:01", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:01", "yyyy.MM.dd-HH:mm"), 18.0, 40.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:01", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:01", "yyyy.MM.dd-HH:mm"), 92.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-16:03", "yyyy.MM.dd-HH:mm"), 3.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-16:06", "yyyy.MM.dd-HH:mm"), 212.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-16:07", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-16:10", "yyyy.MM.dd-HH:mm"), 215.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:11", "yyyy.MM.dd-HH:mm"), 69.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:11", "yyyy.MM.dd-HH:mm"), 86.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:11", "yyyy.MM.dd-HH:mm"), 14.0, 41.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:21", "yyyy.MM.dd-HH:mm"), 15.0, 63.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:21", "yyyy.MM.dd-HH:mm"), 81.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:21", "yyyy.MM.dd-HH:mm"), 52.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-16:25", "yyyy.MM.dd-HH:mm"), 226.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:31", "yyyy.MM.dd-HH:mm"), 86.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:31", "yyyy.MM.dd-HH:mm"), 14.0, 47.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:31", "yyyy.MM.dd-HH:mm"), 86.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:31", "yyyy.MM.dd-HH:mm"), 64.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-16:40", "yyyy.MM.dd-HH:mm"), 249.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:41", "yyyy.MM.dd-HH:mm"), 49.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:41", "yyyy.MM.dd-HH:mm"), 13.0, 67.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:41", "yyyy.MM.dd-HH:mm"), 49.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:41", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-16:51", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:51", "yyyy.MM.dd-HH:mm"), 13.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-16:51", "yyyy.MM.dd-HH:mm"), 13.0, 99.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-16:51", "yyyy.MM.dd-HH:mm"), 25.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-16:55", "yyyy.MM.dd-HH:mm"), 272.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-17:00", "yyyy.MM.dd-HH:mm"), 0.8));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-17:01", "yyyy.MM.dd-HH:mm"), 49.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-17:01", "yyyy.MM.dd-HH:mm"), 12.0, 68.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:01", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-17:10", "yyyy.MM.dd-HH:mm"), 284.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-17:11", "yyyy.MM.dd-HH:mm"), 12.0, 36.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:11", "yyyy.MM.dd-HH:mm"), 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-17:11", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-17:21", "yyyy.MM.dd-HH:mm"), 73.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:21", "yyyy.MM.dd-HH:mm"), 78.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-17:21", "yyyy.MM.dd-HH:mm"), 11.0, 35.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-17:22", "yyyy.MM.dd-HH:mm"), 3.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-17:25", "yyyy.MM.dd-HH:mm"), 292.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-17:26", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:31", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-17:40", "yyyy.MM.dd-HH:mm"), 11.0, 75.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-17:40", "yyyy.MM.dd-HH:mm"), 43.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-17:40", "yyyy.MM.dd-HH:mm"), 304.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:41", "yyyy.MM.dd-HH:mm"), 84.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-17:50", "yyyy.MM.dd-HH:mm"), 60.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-17:50", "yyyy.MM.dd-HH:mm"), 11.0, 53.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-17:51", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-17:55", "yyyy.MM.dd-HH:mm"), 316.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:00", "yyyy.MM.dd-HH:mm"), 11.0, 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:00", "yyyy.MM.dd-HH:mm"), 46.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-18:00", "yyyy.MM.dd-HH:mm"), 0.9));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-18:01", "yyyy.MM.dd-HH:mm"), 75.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:10", "yyyy.MM.dd-HH:mm"), 48.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-18:10", "yyyy.MM.dd-HH:mm"), 323.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:10", "yyyy.MM.dd-HH:mm"), 11.0, 69.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-18:11", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:20", "yyyy.MM.dd-HH:mm"), 46.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:20", "yyyy.MM.dd-HH:mm"), 11.0, 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-18:21", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-18:25", "yyyy.MM.dd-HH:mm"), 325.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-18:30", "yyyy.MM.dd-HH:mm"), 323.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-18:31", "yyyy.MM.dd-HH:mm"), 325.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:31", "yyyy.MM.dd-HH:mm"), 11.0, 82.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-18:31", "yyyy.MM.dd-HH:mm"), 95.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:31", "yyyy.MM.dd-HH:mm"), 38.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-18:38", "yyyy.MM.dd-HH:mm"), 325.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-18:38", "yyyy.MM.dd-HH:mm"), 325.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-18:39", "yyyy.MM.dd-HH:mm"), 1.17));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-18:40", "yyyy.MM.dd-HH:mm"), 323.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:41", "yyyy.MM.dd-HH:mm"), 10.0, 52.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:41", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-18:41", "yyyy.MM.dd-HH:mm"), 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-18:41", "yyyy.MM.dd-HH:mm"), 3.4));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-18:51", "yyyy.MM.dd-HH:mm"), 32.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-18:51", "yyyy.MM.dd-HH:mm"), 10.0, 90.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-18:55", "yyyy.MM.dd-HH:mm"), 327.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-19:00", "yyyy.MM.dd-HH:mm"), 1.3));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:01", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-19:09", "yyyy.MM.dd-HH:mm"), 306.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-19:11", "yyyy.MM.dd-HH:mm"), 311.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:11", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-19:11", "yyyy.MM.dd-HH:mm"), 35.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-19:11", "yyyy.MM.dd-HH:mm"), 10.0, 86.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-19:17", "yyyy.MM.dd-HH:mm"), 308.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-19:18", "yyyy.MM.dd-HH:mm"), 311.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-19:18", "yyyy.MM.dd-HH:mm"), 311.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-19:20", "yyyy.MM.dd-HH:mm"), 2.6));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:21", "yyyy.MM.dd-HH:mm"), 65.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-19:25", "yyyy.MM.dd-HH:mm"), 288.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-19:30", "yyyy.MM.dd-HH:mm"), 10.0, 90.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-19:30", "yyyy.MM.dd-HH:mm"), 32.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:31", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-19:32", "yyyy.MM.dd-HH:mm"), 279.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-19:40", "yyyy.MM.dd-HH:mm"), 40.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-19:40", "yyyy.MM.dd-HH:mm"), 10.0, 79.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-19:40", "yyyy.MM.dd-HH:mm"), 270.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:41", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-19:42", "yyyy.MM.dd-HH:mm"), 3.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-19:46", "yyyy.MM.dd-HH:mm"), 6.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-19:51", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-19:51", "yyyy.MM.dd-HH:mm"), 10.0, 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-19:51", "yyyy.MM.dd-HH:mm"), 43.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-19:55", "yyyy.MM.dd-HH:mm"), 244.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-20:00", "yyyy.MM.dd-HH:mm"), 1.3));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:01", "yyyy.MM.dd-HH:mm"), 10.0, 88.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:01", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:01", "yyyy.MM.dd-HH:mm"), 34.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-20:10", "yyyy.MM.dd-HH:mm"), 231.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:11", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:11", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:11", "yyyy.MM.dd-HH:mm"), 42.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:11", "yyyy.MM.dd-HH:mm"), 10.0, 77.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:21", "yyyy.MM.dd-HH:mm"), 67.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:21", "yyyy.MM.dd-HH:mm"), 10.0, 87.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:21", "yyyy.MM.dd-HH:mm"), 34.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-20:25", "yyyy.MM.dd-HH:mm"), 227.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:31", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:31", "yyyy.MM.dd-HH:mm"), 10.0, 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:31", "yyyy.MM.dd-HH:mm"), 46.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-20:40", "yyyy.MM.dd-HH:mm"), 209.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:41", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:41", "yyyy.MM.dd-HH:mm"), 11.0, 141.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:41", "yyyy.MM.dd-HH:mm"), 14.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 12.0, 88.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 34.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 34.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-20:51", "yyyy.MM.dd-HH:mm"), 195.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-20:55", "yyyy.MM.dd-HH:mm"), 188.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-21:00", "yyyy.MM.dd-HH:mm"), 1.3));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:01", "yyyy.MM.dd-HH:mm"), 12.0, 88.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:01", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:01", "yyyy.MM.dd-HH:mm"), 34.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:01", "yyyy.MM.dd-HH:mm"), 12.0, 88.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-21:10", "yyyy.MM.dd-HH:mm"), 170.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:11", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:11", "yyyy.MM.dd-HH:mm"), 12.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:11", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:21", "yyyy.MM.dd-HH:mm"), 12.0, 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:21", "yyyy.MM.dd-HH:mm"), 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:21", "yyyy.MM.dd-HH:mm"), 45.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-21:23", "yyyy.MM.dd-HH:mm"), 165.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-21:25", "yyyy.MM.dd-HH:mm"), 161.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:31", "yyyy.MM.dd-HH:mm"), 36.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:31", "yyyy.MM.dd-HH:mm"), 12.0, 85.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:31", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-21:40", "yyyy.MM.dd-HH:mm"), 153.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:41", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:41", "yyyy.MM.dd-HH:mm"), 43.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:41", "yyyy.MM.dd-HH:mm"), 12.0, 76.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-21:51", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-21:51", "yyyy.MM.dd-HH:mm"), 12.0, 92.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-21:51", "yyyy.MM.dd-HH:mm"), 31.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-21:55", "yyyy.MM.dd-HH:mm"), 143.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-22:00", "yyyy.MM.dd-HH:mm"), 142.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-22:00", "yyyy.MM.dd-HH:mm"), 1.3));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:01", "yyyy.MM.dd-HH:mm"), 30.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:01", "yyyy.MM.dd-HH:mm"), 12.0, 93.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:01", "yyyy.MM.dd-HH:mm"), 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-22:09", "yyyy.MM.dd-HH:mm"), 142.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:11", "yyyy.MM.dd-HH:mm"), 40.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:11", "yyyy.MM.dd-HH:mm"), 40.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:11", "yyyy.MM.dd-HH:mm"), 13.0, 79.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-22:11", "yyyy.MM.dd-HH:mm"), 139.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:11", "yyyy.MM.dd-HH:mm"), 73.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-22:19", "yyyy.MM.dd-HH:mm"), 139.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-22:19", "yyyy.MM.dd-HH:mm"), 1.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-22:19", "yyyy.MM.dd-HH:mm"), 139.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-22:20", "yyyy.MM.dd-HH:mm"), 2.4));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:21", "yyyy.MM.dd-HH:mm"), 13.0, 71.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:21", "yyyy.MM.dd-HH:mm"), 80.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:21", "yyyy.MM.dd-HH:mm"), 46.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-22:24", "yyyy.MM.dd-HH:mm"), 145.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-22:25", "yyyy.MM.dd-HH:mm"), 139.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.MEAL_BOLUS_CALCULATOR, TimestampUtils.createCleanTimestamp("2017.06.01-22:25", "yyyy.MM.dd-HH:mm"), 1.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.BOLUS_NORMAL, TimestampUtils.createCleanTimestamp("2017.06.01-22:26", "yyyy.MM.dd-HH:mm"), 2.2));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:31", "yyyy.MM.dd-HH:mm"), 35.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:31", "yyyy.MM.dd-HH:mm"), 13.0, 86.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:31", "yyyy.MM.dd-HH:mm"), 70.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-22:40", "yyyy.MM.dd-HH:mm"), 164.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:41", "yyyy.MM.dd-HH:mm"), 13.0, 81.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:41", "yyyy.MM.dd-HH:mm"), 39.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:41", "yyyy.MM.dd-HH:mm"), 72.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-22:45", "yyyy.MM.dd-HH:mm"), 173.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-22:51", "yyyy.MM.dd-HH:mm"), 33.25));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-22:51", "yyyy.MM.dd-HH:mm"), 13.0, 89.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-22:51", "yyyy.MM.dd-HH:mm"), 69.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-22:55", "yyyy.MM.dd-HH:mm"), 189.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-23:00", "yyyy.MM.dd-HH:mm"), 1.235));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-23:01", "yyyy.MM.dd-HH:mm"), 31.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:01", "yyyy.MM.dd-HH:mm"), 67.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-23:01", "yyyy.MM.dd-HH:mm"), 13.0, 91.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-23:09", "yyyy.MM.dd-HH:mm"), 200.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-23:10", "yyyy.MM.dd-HH:mm"), 200.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-23:11", "yyyy.MM.dd-HH:mm"), 14.0, 56.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-23:11", "yyyy.MM.dd-HH:mm"), 58.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:11", "yyyy.MM.dd-HH:mm"), 80.0));
        tmpAnnotations = new ArrayList<>();
        tmpAnnotations.add(new VaultEntryAnnotation(VaultEntryAnnotation.TYPE.GLUCOSE_BG_METER_SERIAL));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BG, TimestampUtils.createCleanTimestamp("2017.06.01-23:19", "yyyy.MM.dd-HH:mm"), 202.0, tmpAnnotations));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_BOLUS_CALCULATION, TimestampUtils.createCleanTimestamp("2017.06.01-23:20", "yyyy.MM.dd-HH:mm"), 202.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_MANUAL, TimestampUtils.createCleanTimestamp("2017.06.01-23:20", "yyyy.MM.dd-HH:mm"), 1.045));
        vaultEntries.add(new VaultEntry(VaultEntryType.BASAL_PROFILE, TimestampUtils.createCleanTimestamp("2017.06.01-23:20", "yyyy.MM.dd-HH:mm"), 0.95));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:21", "yyyy.MM.dd-HH:mm"), 74.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-23:25", "yyyy.MM.dd-HH:mm"), 203.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:31", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-23:40", "yyyy.MM.dd-HH:mm"), 37.75));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM_ALERT, TimestampUtils.createCleanTimestamp("2017.06.01-23:40", "yyyy.MM.dd-HH:mm"), 185.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-23:40", "yyyy.MM.dd-HH:mm"), 184.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-23:40", "yyyy.MM.dd-HH:mm"), 12.0, 83.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:41", "yyyy.MM.dd-HH:mm"), 61.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.STRESS, TimestampUtils.createCleanTimestamp("2017.06.01-23:50", "yyyy.MM.dd-HH:mm"), 26.5));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE_VARIABILITY, TimestampUtils.createCleanTimestamp("2017.06.01-23:50", "yyyy.MM.dd-HH:mm"), 13.0, 98.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.HEART_RATE, TimestampUtils.createCleanTimestamp("2017.06.01-23:51", "yyyy.MM.dd-HH:mm"), 60.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.SLEEP_LIGHT, TimestampUtils.createCleanTimestamp("2017.06.01-23:55", "yyyy.MM.dd-HH:mm"), 14.0));
        vaultEntries.add(new VaultEntry(VaultEntryType.GLUCOSE_CGM, TimestampUtils.createCleanTimestamp("2017.06.01-23:55", "yyyy.MM.dd-HH:mm"), 185.0));
        return vaultEntries;
    }
}
